### ISSUE TITLE
viewer crashes when pressing the "detail" and "report" options

### ISSUE THREAD

**Issue by Arhabditis** [blobtoolkit/blobtools2#1]
The BlobToolKit Viewer is crashing when I press the "detail" and "report" options in the Settings tab. The viewer freezes and I'm not able to load any of the other options in Settings unless I refresh the page while selecting one of the other options.

**Comment by rjchallis** [comment]
Thanks for the first bug report!

This is now fixed in the [viewer (2172d98)](https://github.com/blobtoolkit/viewer/commit/2172d98ad8a052d8534f9c077d73c1c9cdb8ccce)
