### ISSUE TITLE
WARN: Skipping field 'bestsum_phylum', not present in dataset

### ISSUE THREAD

**Issue by st303118** [blobtoolkit/blobtools2#11]
Hello,
I have a proper blobdir and all the datasets inside dir with .json extension.
I want to filter the my reads and get those belonging to only one phylum. 
I used this command: ./blobtools filter --param -param bestsum_phylum--Keys=Rhodophyta --fastq reads_1.fq --fastq reads_2.fq --cov examples/assembly.reads.bam  tmp/dataset_2
I have files named bestsumorder_*.json.
I also tried using bestsumorder_phylum and ended up with same error. Is it possible to extract the bam coverage file using the command above? If yes, what might have gone wrong there? Thank you.

**Comment by rjchallis** [comment]
blob tools filter should extract the reads that map to contains assigned to a phylum using a command similar to the one you have used. I'm not sure why you would get that error if you have a complete BlobDir (I'm assuming that the -param in your command above isn't in the command you ran as that would cause a different error). 

Could you paste the output of `ls tmp/dataset_2` and attach the full `tmp/dataset_2/meta.json` so I can check everything seems to have been added as expected.

A couple of other comments based on the example command that may help you to get what you want when filtering:
- `--param bestsum_phylum--Keys=Rhodophyta` will filter out any sequences that match Rhodophyta,to keep them you would need to add a `--param bestsum_phylum--Inv=true` to invert that filter.
- `--fastq reads_1.fq` will look for the reads in the current directory, you may need to add the path to the read files if they are in another directory.

**Comment by st303118** [comment]
Great. Thank you for your kind response. I also used --query-string "path/to/blobtoolkit/viewer/with/filter/applied" and extracted the reads. I realized there was a problem with blobdir path I provided. Now it works. Thank you for this amazing tool.
