### ISSUE TITLE
Blobtools2 view issue

### ISSUE THREAD

**Issue by black1414** [blobtoolkit/blobtools2#14]
Hello,
I am trying to view / filter a blob directory locally on my macOS but firefox is having issues finding the blob directory.

I have two terminals open:
1) I ran the following command within conda env:
$BTK_FILE_PATH=/Users/black_cgrb/wp4_blob_data npm start

And received the following output:
> blobtoolkit-viewer@1.1.0 start /Users/black_cgrb/blobtoolkit/viewer
> nodemon src/server/app.js

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/server/app.js`
BlobToolKit RESTful API server started on http port: 8000

For the second terminal that I typed the following:
$npm run client

Which showed the following tail output:    

Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js!./node_modules/sass-loader/dist/cjs.js!./src/client/views/components/Tree.scss] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/client/views/components/Tree.scss 7.09 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.46 KiB {mini-css-extract-plugin} [built]
ℹ ｢wdm｣: Compiled successfully.

When I open up "http://localhost:8080/view/all/" I am able to view the different pull down options from blobtools, but get the error message: "Dataset wp4_blob_data could not be found"

Can you help?
Thank you!
-Andrew

**Comment by rjchallis** [comment]
You have dollar sign at the start of `$BTK_FILE_PATH=/Users/black_cgrb/wp4_blob_data npm start`, if this isn't a typo then that would mean that `BTK_FILE_PATH` wasn't actually set. In that case `BTK_FILE_PATH=/Users/black_cgrb/wp4_blob_data npm start` would be the command you need.

The other potential problem is that `BTK_FILE_PATH should be the path to the parent directory of your BlobDir, so if `/Users/black_cgrb/wp4_blob_data` is the BlobDir directory that contains the various JSON files, the `npm start` command should actually be:

```
BTK_FILE_PATH=/Users/black_cgrb npm start
```

You may find that you need to nest the BlobDir inside another directory if it has problems hosting `/Users/black_cgrb` directly.

**Comment by black1414** [comment]
The "$' was just an example, not specifying that it was already an env variable, but nesting the BlobDir inside another directory (as done in the tutorial) worked liked a charm; it loaded perfectly into viewer.

As a follow up, I have a separate question relating to filtering out sequences:

Does specifying the 'bestsum_order_key" parameter within the 'filter' module remove the entire contig(s) or just the portion of a contig attributed to a particular taxa?

For example, I used the viewer options to identify non-target phylum and then ran the following command locally:

~/blobtoolkit/blobtools2/blobtools filter --query-string "bestsumorder_phylum--Keys=no-hit&bestsumorder_phylum--Keys=Arthropoda&bestsumorder_phylum--Keys=Chytridiomycota" --fasta ~/DATASETS/FILES/ASSEMBLY_NAME.fasta ~/DATASETS/ASSEMBLY_NAME

While there were four identified contigs (belonging to the non-target taxon) the above command only filtered out one contig from my assembly. Do you believe that the other three parameters weren't interpreted?

Thank you!
-Andrew

**Comment by rjchallis** [comment]
Glad that worked!

The filter command will remove whole configs so it looks like some of the parameters were not interpreted. I hadn't tested with that query string syntax (though out looks valid) but a more compact form should hopefully work:

```
~/blobtoolkit/blobtools2/blobtools filter --query-string "bestsumorder_phylum--Keys,Arthropoda,Chytridiomycota" --fasta ~/DATASETS/FILES/ASSEMBLY_NAME.fasta ~/DATASETS/ASSEMBLY_NAME
```

**Comment by black1414** [comment]
Excellent, I'll give that a shot! Thank you for your support and for developing such an awesome toolkit, much appreciated!
Best,
-Andrew
