### ISSUE TITLE
Format Uniprot database not working

### ISSUE THREAD

**Issue by dianamosa** [blobtoolkit/blobtools2#19]
Hello,
I am installing blobtools2 but I am having issues with fetching my UniProt database. My code is:

```
wget -q -O uniprot/reference_proteomes.tar.gz \
 ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/$(curl \
     -vs ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/ 2>&1 | \
     awk '/tar.gz/ {print $9}')
```

I was able to create the reference_proteomes.fasta.gz file. But I had issues creating the reference_proteomes.taxid_map file

The following command is not working:
```
zcat */*/*.idmapping.gz | grep "NCBI_TaxID" | awk '{print $1 "\t" $1 "\t" $3 "\t" 0}' >> reference_proteomes.taxid_map
```

The error is Unexpected end of file, I downloaded again the Uniprot database, in case the files were incomplete, and I had the same error.

Any thoughts about this issue?

Thank you.

**Comment by rjchallis** [comment]
I'm not able to reproduce this, I just downloaded the `reference_proteomes.tar.gz`, and didn't encounter any errors running:
```
zcat */*/*.idmapping.gz | grep "NCBI_TaxID" | awk '{print $1 "\t" $1 "\t" $3 "\t" 0}' >> reference_proteomes.taxid_map
```

An unexpected end of file error in that command would suggest that one of the individual *.idmapping.gz files is incomplete, which seems odd. One possibility is that you are running into disk space/quota issues and the tar extraction is incomplete, but errors associated with that should have shown up sooner.

I've run `ls -l` and `du -s *` on the uniprot directory so you can see the file sizes that I have, in case that helps with working out where any incomplete files may be:

```
ubuntu@btk:/volumes/data/databases/uniprot$ ls -l
total 119420720
drwxr-xr-x  327 ubuntu ubuntu        12288 Feb  8 17:10 Archaea
drwxr-xr-x 7945 ubuntu ubuntu       253952 Feb  8 17:56 Bacteria
drwxr-xr-x 1556 ubuntu ubuntu        45056 Feb  8 18:01 Eukaryota
-rw-r--r--    1 ubuntu ubuntu      1485789 Feb  8 15:52 README
drwxr-xr-x 9865 ubuntu ubuntu       266240 Feb  8 19:29 Viruses
-rw-rw-r--    1 ubuntu ubuntu 120567805503 Feb 10 22:31 reference_proteomes.tar.gz
-rw-rw-r--    1 ubuntu ubuntu   1716907359 Mar  4 09:42 reference_proteomes.taxid_map

ubuntu@btk:/volumes/data/databases/uniprot$ du -s *
1255924 Archaea
54915864        Bacteria
61331096        Eukaryota
1452    README
804304  Viruses
117742024       reference_proteomes.tar.gz
1676672 reference_proteomes.taxid_map
```
