### ISSUE TITLE
add --busco error with examples dataset

### ISSUE THREAD

**Issue by pbaCamille** [blobtoolkit/blobtools2#2]
Hello,
I'm actually testing your tool with the data included in the examples/ folder. But the cmd 
```
blobtools add --busco examples/busco.tsv AssemblyName 
```
return the following message:
```
Traceback (most recent call last):
  File "/home/trottier-c/Documents/blobtools2/lib/add.py", line 131, in <module>
    main()
  File "/home/trottier-c/Documents/blobtools2/lib/add.py", line 98, in main
    meta=meta)
  File "/home/trottier-c/Documents/blobtools2/lib/busco.py", line 49, in parse
    parsed.append(parse_busco(file, identifiers=kwargs['dependencies']['identifiers']))
  File "/home/trottier-c/Documents/blobtools2/lib/busco.py", line 22, in parse_busco
    meta['set'] = re.search(r'-l.+\/(\w+_odb\d+)\/', meta['command'])[1]
TypeError: 'NoneType' object is not subscriptable
```
Thanks

**Comment by rjchallis** [comment]
Thanks for pointing this out - it seems that I was expecting a leading slash in the path to the BUSCO lineage even though my example file has no such slash.  I think the updated regex should be more robust.

**Comment by Jadziaa** [comment]
Hello,

I am having problem with adding BUSCO results to my BlobDir. This is my cmd:

../../tools/blobtools2/blobtools add --busco chinease_busco/run_metazoa_odb10/full_table.tsv CHINEASE/

and the error message:

Traceback (most recent call last):
  File "/Data/jadzia/tools/blobtools2/lib/add.py", line 147, in <module>
    main()
  File "/Data/jadzia/tools/blobtools2/lib/add.py", line 114, in main
    meta=meta)
  File "/Data/jadzia/tools/blobtools2/lib/busco.py", line 49, in parse
    parsed.append(parse_busco(file, identifiers=kwargs['dependencies']['identifiers']))
  File "/Data/jadzia/tools/blobtools2/lib/busco.py", line 19, in parse_busco
    'command': lines[2].split(':')[1].strip(),
IndexError: list index out of range

I would be grateful for any informations.

**Comment by rjchallis** [comment]
Hi

From the odb10 lineage name, I'm assuming that you have run BUSCO v4. I've not actually tested this yet as there were a few reports of problems with the initial release so I was waiting for things to settle down. The import parses some values from the file header that have presumably moved around in the latest version.

I'll do a test run in the next few days and take a look at what needs to change to get the import working. If you could share the first few lines of your output tsv, I could take a look sooner and hopefully find a way to get this working again.

**Comment by Jadziaa** [comment]
Thanks for your quick respond. Indeed, the output file produced by BUSCO v4. is little bit different than the one in example:

# BUSCO version is: 4.0.2
# The lineage dataset is: metazoa_odb10 (Creation date: 2019-11-20, number of species: 65, number of BUSCOs: 954)
# Busco id	Status	Sequence	Gene Start	Gene End	Score	Length
5951at33208a	Complete	NW_017545502.1:996991-1011040	996991	1011040	4366.1	2082
9639at33208a	Complete	NC_031728.1:16590681-16599049	16590681	16599049	1247.3	707
9639at33208a	Complete	NC_031728.1:16544518-16560864	16544518	16560864	1191.3	786
9639at33208a	Complete	NW_017545308.1:369178-377546	369178	377546	1247.3	707
9639at33208a	Complete	NW_017545308.1:323015-339361	323015	339361	1191.3	786
13816at33208a	Complete	NW_017538059.1:42873-85704	42873	85704	1055.9	1044
14776at33208a	Complete	NW_017539969.1:207686-236481	207686	236481	1912.9	1075

**Comment by rjchallis** [comment]
Thanks, looks like this should be straightforward to fix.

The v3 files used to include the command that was run and I parsed the lineage from there as nematoda_odb9 used to be misreported as metazoa_odb9 in some versions. I'll test for the version and parse the summary instead for v4.

**Comment by rjchallis** [comment]
Importing BUSCO v4 files should now be working.

**Comment by Jadziaa** [comment]
Thanks a lot! It works like a dream :)

**Comment by Alonso-Garcia** [comment]
Hello, 
I first wanted to thank you for the software and for help us with all our questions.

I'm also having problems to add my busco results (full_table.tsv) to the BlobDir. I'm using busco/5.0.0 and different lineages (odb10). 

This is my busco v.5 code:
```
## eukaryota_odb10 
busco -m genome \
	-i $src/DNA/04_assembly_DNA/metaSPAdes_output_518_t2/contigs.fasta \
	-o 518_busco_DNA \
	-l eukaryota_odb10 \
	--augustus 

## bacteria_odb10 
busco -m genome \
	-i $src/DNA/04_assembly_DNA/metaSPAdes_output_518_t2/contigs.fasta \
	-o 518_busco_Bact_DNA \
	-l bacteria_odb10 \
```

En here you have the command to add the results: 
```
//prg/blobtools/2/blobtools2/blobtools add \
  --busco ~/DNA/06_busco/518_busco_Euka_DNA/run_eukaryota_odb10/full_table.tsv \
   ~/DNA/05_BlobDir/518_DNA_BlobDir

//prg/blobtools/2/blobtools2/blobtools add \
  --busco ~/DNA/06_busco/518_busco_Bact_DNA/bacteria_odb10/full_table.tsv \
    ~/DNA/05_BlobDir/518_DNA_BlobDir
```
Results for eukaryota_odb10 are added to my BlobDir. However, when I try to add the  bacteria_odb10, I have this error:
```
Traceback (most recent call last):
  File "//prg/blobtools/2/blobtools2/lib/add.py", line 165, in <module>
    main()
  File "//prg/blobtools/2/blobtools2/lib/add.py", line 132, in main
    meta=meta)
  File "/prg/blobtools/2/blobtools2/lib/busco.py", line 63, in parse
    parsed.append(parse_busco(file, identifiers=kwargs['dependencies']['identifiers']))
  File "/prg/blobtools/2/blobtools2/lib/busco.py", line 47, in parse_busco
    raise UserWarning('Contig names in the Busco file did not match dataset identifiers.')
UserWarning: Contig names in the Busco file did not match dataset identifiers.
```

Do you think it is due to my data? I have maybe done something wrong using Busco for bacteria_odb10. In fact, I have the same error for archae and alphaproteobacteria, but it works well for fungi, chlorophyta. I would really appreciate if you could let me know how to solve it :) 
Thank you very much! 
Marta

**Comment by rjchallis** [comment]
I've not run this with Busco v5 yet, or with the bacteria busco set so I don't know exactly what is causing the problem here - could you share the first few lines of each file so I can look to see if there is anything obvious?

**Comment by Alonso-Garcia** [comment]
Thank you for your quick answer. 

Here you have the first lines of the file (full_table.tsv) generated by busco v5 for bacteria (`-l bacteria_odb10 `). **I can not add it to BlobDir**
```
# BUSCO version is: 5.0.0 
# The lineage dataset is: bacteria_odb10 (Creation date: 2020-03-06, number of species: 4085, number of BUSCOs: 124)
# Busco id	Status	Sequence	Gene Start	Gene End	Strand	Score	Length	OrthoDB url	Description
4421at2	Fragmented	NODE_69_length_176844_cov_138.180232_54	79150	84813	-	504.4	455	https://www.orthodb.org/v10?query=4421at2	DNA-directed RNA polymerase subunit beta'
9601at2	Complete	NODE_69_length_176844_cov_138.180232_56	85450	90522	-	800.4	766	https://www.orthodb.org/v10?query=9601at2	DNA-directed RNA polymerase subunit beta
26038at2	Fragmented	NODE_56_length_226981_cov_26.278532_274	163671	165086	-	133.2	184	https://www.orthodb.org/v10?query=26038at2	phosphoribosylformylglycinamidine synthase
91428at2	Fragmented	NODE_15_length_499517_cov_26.539204_155	104390	106831	+	327.5	453	https://www.orthodb.org/v10?query=91428at2	alanine--tRNA ligase
95696at2	Missing
143460at2	Missing
182107at2	Missing
219876at2	Missing
223233at2	Fragmented	NODE_26594_length_745_cov_0.860841_1	3	743	-	132.2	151	https://www.orthodb.org/v10?query=223233at2	DNA topoisomerase I
226836at2	Missing
232152at2	Fragmented	NODE_32517_length_636_cov_0.905697_1	2	634	+	128.6	122	https://www.orthodb.org/v10?query=232152at2	adenylosuccinate synthase
267682at2	Fragmented	NODE_13_length_524813_cov_24.112791_58	63486	63806	+	74.4	64	https://www.orthodb.org/v10?query=267682at2	amidophosphoribosyltransferase
353391at2	Complete	NODE_81_length_139772_cov_18.442601_72	106034	108076	+	194.3	292	https://www.orthodb.org/v10?query=353391at2	serine--tRNA ligase
384865at2	Fragmented	NODE_34851_length_603_cov_1.142857_1	1	603	-	100.4	78	https://www.orthodb.org/v10?query=384865at2	Transcription termination/antitermination protein NusA
402899at2	Fragmented	NODE_56903_length_428_cov_1.551495_1	1	426	-	76.0	88	https://www.orthodb.org/v10?query=402899at2	tyrosine--tRNA ligase
430176at2	Complete	NODE_69_length_176844_cov_138.180232_49	63139	64602	-	562.5	359	https://www.orthodb.org/v10?query=430176at2	ATP synthase subunit beta
462069at2	Complete	NODE_52_length_232158_cov_26.536062_270	171211	172362	-	116.4	198	https://www.orthodb.org/v10?query=462069at2	phosphoglycerate kinase
```

And this is the file generated by busco v5 for Eukariotas. **I can add it to the BlobDir.**  

```
# BUSCO version is: 5.0.0 
# The lineage dataset is: eukaryota_odb10 (Creation date: 2020-09-10, number of species: 70, number of BUSCOs: 255)
# Busco id	Status	Sequence	Gene Start	Gene End	Strand	Score	Length
39650at2759	Complete	NODE_61_length_215307_cov_26.637452	119693	126669	+	2105.0	1421
83779at2759	Complete	NODE_25_length_385454_cov_25.561783	248119	251791	-	233.7	224
87842at2759	Complete	NODE_67_length_178363_cov_27.274131	41366	47001	+	543.2	583
97116at2759	Complete	NODE_32_length_353141_cov_24.859484	127175	131541	+	1194.6	954
100698at2759	Complete	NODE_85_length_132933_cov_24.389320	45486	48617	+	801.4	499
142542at2759	Complete	NODE_12_length_546856_cov_25.532480	299506	307873	-	512.4	560
156083at2759	Complete	NODE_1_length_1010648_cov_26.219626	187543	195091	-	3615.6	1944
160593at2759	Complete	NODE_139_length_39920_cov_17.621441	17625	27419	+	1456.2	1318
166920at2759	Complete	NODE_6_length_630289_cov_26.683412	339059	349005	-	640.4	746
176625at2759	Complete	NODE_46_length_247800_cov_25.144820	49632	53250	-	306.4	461
179362at2759	Complete	NODE_1_length_1010648_cov_26.219626	971663	976975	-	673.6	1090
```

Thanks again, and pleases, let me know if you need something else. 
Regards!

**Comment by rjchallis** [comment]
Looks like the problem is that all the sequence names in the eukaryota file have names like `NODE_61_length_215307_cov_26.637452`, but the ones in the bacteria file have an extra number appended at the end (e.g. `NODE_69_length_176844_cov_138.180232_54`) so they don't match you input sequence names exactly. 

Not sure why this is, but I expect that the bacteria results should import if you were to remove this trailing number.

**Comment by Alonso-Garcia** [comment]
Thank you rjchallis, 
As you said, it works if I remove them.  Anyway, I'll let you know if I find a way to avoid that change on contig names. It would be easier. 
Regards!

**Comment by Alonso-Garcia** [comment]
Here we have the reason of the change on contig names: 
https://gitlab.com/ezlab/busco/-/issues/411#note_521116000
Thanks again!
