### ISSUE TITLE
Filter by scaffold ID

### ISSUE THREAD

**Issue by faguil** [blobtoolkit/blobtools2#20]
Hi,

Thanks for such great software. I am wondering if it is possible to filter an assembly based on scaffold ID.

I have tried to do it using the list option, but it did not work. 

Any help/advice would be really appreciated. 

Best,

**Comment by rjchallis** [comment]
Hi

To filter an assembly fasta, you should be able to do something like:

```file.txt
seq1
seq2
seq3
```

```
blobtools filter --list /path/to/list/file.txt --fasta /path/to/assembly.fasta /path/to/blobdir/dataset
```

or 

```file.json
{
  "identifiers": [
    "seq1",
    "seq2",
    "seq3"
  ]
}
```

```
blobtools filter --json /path/to/list/file.json --fasta /path/to/assembly.fasta /path/to/blobdir/dataset
```

**Comment by faguil** [comment]
thanks for your reply. I did the json option and it worked.
