### ISSUE TITLE
how to filter with an OR of conditions?

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/blobtools2#21]
Hi Rich,

I would like to filter out any sequence that matches any of these two conditions: 1) bestsumorder_superkingdom--Keys=Bacteria or 2) bestsumorder_superkingdom--Keys=no-hit & gc--Min=0.49. 

A simple way would be to filter with one condition and then filter the resulting set with the second condition. Is there a way of achieving the OR in a single query?

Best,
Pablo

**Comment by rjchallis** [comment]
Hi Pablo

There's no way to do that in one query, so you'll have to filter twice .

**Comment by pgonzale60** [comment]
Thank you for clarifying.
