### ISSUE TITLE
multiple bam files

### ISSUE THREAD

**Issue by pbaCamille** [blobtoolkit/blobtools2#3]
Hello,

I was wondering if it is possible to add multiple bam files, i have one file per sample. If i use 
```
blobtools create --fasta <assembly.fasta> --cov sample1.bam --cov sample2.bam etc.
```
when i look in the meta.json file, it seems to only replace sample1.bam information by sample2.bam.

Thanks in advance for your answer.

**Comment by rjchallis** [comment]
Hi

Adding multiple BAM files should work exactly as you were expecting. I've just tried testing with BAM files named `sample1.bam` and `sample2.bam` in case of a filename-related bug, but i can't reproduce a problem.

I'm guessing that what may be happening is that the second BAM file has a wider range of values than the first, in which case the `base_coverage` `range` should be updated as it is set to the maximum range of all input files. These fields are given a single range so the y-axis scale can remain consistent when switching between coverage libraries in the viewer.

If this is the case, there should still be a separate entry for each file in `meta.json`:
```
...
{
  "id":"base_coverage",
  "clamp":false,
  "range":[
   41.4191,
   48.3659
  ],
  "children":[
    {
      "id":"sample1_cov",
      "file":"sample1.bam",
      "type":"variable"
     },
     {
       "id":"sample2_cov",
       "file":"sample2.bam",
       "type":"variable"
     }
   ]
},
...
```

The `read_coverage` should also have a single `range`, but each file should have its own `reads_mapped` and `reads_unmapped` values:

```
...
{
  "id":"read_coverage",
  "datatype":"integer",
  "clamp":false,
  "range":[
    4162,
    1605722
  ],
  "children":[
    {
      "id":"sample1_read_cov",
      "file":"sample1.bam",
      "reads_mapped":6549966,
      "reads_unmapped":1067702,
      "type":"variable"
    },
    {
      "id":"sample2_read_cov",
      "file":"sample2.bam",
      "reads_mapped":6786209,
      "reads_unmapped":780006,
      "type":"variable"
    }
  ]
}
...
```

Hopefully this explains the behaviour you are seeing. If not, could you let me see your `meta.json` file so I can try to investigate further.

**Comment by pbaCamille** [comment]
Thank your for your answer.
I have trying with example bam files here ( https://github.com/DRL/blobtools/blob/master/example/mapping_1.sorted.bam and mapping_2.sorted.bam). and the resulting meta.json file, only contains entry for the second bam file (File attached).
I think there is an issue regarding the "id". In my case, even if i change the input bam file, the entry id is always the same 
```
"children":[
      {
       "id":"sorted_cov",
       "file":"test_multiple_bam/mapping_1.sorted.bam",
       "type":"variable",
       "parent":"base_coverage"
      }
     ],
```
[meta.json.txt](https://github.com/blobtoolkit/blobtools2/files/3524092/meta.json.txt)

**Comment by rjchallis** [comment]
Thanks for the extra detail, I can see where the bug lies now. I have a habit of naming bam files `<assembly_name>.<library_name>.bam` so if there is more than one dot in the filename the ID will always be set based on the characters immediately preceding `.bam`. 

As a quick fix, renaming the files `mapping_1.bam` and `mapping_2.bam` would work for this case but this needs fixing in the code so I'll get to work on a more robust solution.

**Comment by pbaCamille** [comment]
Ok great news !
Thank you again.

**Comment by rjchallis** [comment]
latest commit uses the full file basename to set the field name so `mapping_1.sorted.bam` field id will be `mapping_1.sorted`.

To use a different name, specify `=fieldname` after the filename, e.g.
```
--cov mapping_1.sorted.bam=mapping_1 --cov mapping_2.sorted.bam=mapping_2
```
or
```
--cov assembly_name.library_name.bam=library_name
```
