### ISSUE TITLE
Error: Tokenizer Exception for diamond makedb

### ISSUE THREAD

**Issue by upendrabhattarai** [blobtoolkit/blobtools2#30]
Hi,

I was trying to create diamond database following the instructions in [3. Fetch and format the UniProt database](https://blobtoolkit.genomehubs.org/install/)
I came across this error:

```
Writing sequences...  [0.399s]
Writing accessions...  [1.374s]
Hashing sequences...  [0.138s]
Loading sequences...  [0s]
Writing trailer...  [0.897s]
Loading taxonomy...  [0.369s]
Error: Tokenizer Exception
```

Slightly editing
```
echo "accession\taccession.version\ttaxid\tgi" > reference_proteomes.taxid_map
```
to
```
echo -e accession'\t'accession.version'\t'taxid'\t'gi > reference_proteomes.taxid_map
```
got rid of above error.
Thought might help others having similar issue.

Cheers,
Upendra

**Comment by donthuanalyst** [comment]
Thank you Upendra for posting this information. 

I got the same error. I will try your solution.

**Comment by Upe-ndra** [comment]
> Thank you Upendra for posting this information.
> 
> I got the same error. I tried your solution and it worked.
> 
> Thank you for your help.

Glad it helped

Upendra

**Comment by sujaikumar** [comment]
Thank you! We've updated https://blobtoolkit.genomehubs.org/install/ with your fix.

**Comment by azeezoe** [comment]
> Thank you! We've updated https://blobtoolkit.genomehubs.org/install/ with your fix.

Just wanted to update that this change is not reflected on the site.
