### ISSUE TITLE
Installation on Ubuntu 18.04

### ISSUE THREAD

**Issue by tshori** [blobtoolkit/blobtools2#31]
Hi,

I just wanted to leave a note. I installed the toolkit both using conda and manually downloading the packages. In both instances, blobtools create crashed because bed.py is trying to import to file from a module called tolkein. I now realize that you guys also wrote this module. There is a different module for python called tolkien, that has nothing to do with you! Just leaving this here so nobody has to go through the process of realizing that pip was not working because I had misspelled the package name. 

The way I finally figured it out was by running pip install -r requirments.txt, which works like a charm.

You may want to add your tolkein module as a dependency, cause on my system it was not downloaded as part of the installation instructions or conda recipe. 

Cheers,

T.

**Comment by sujaikumar** [comment]
Thanks for clarifying that. Yes, `pip install -r requirements.txt` will take care of that. The pipeline env.yaml now has that explicitly as a requirement https://github.com/blobtoolkit/pipeline/blob/master/env.yaml

**Comment by angusdavison** [comment]
Sorry to open this one again, but I got the same problem - although installation proceeded without any errors, "blobtools create" does not run. Unfortunately, I am not clear how to use @sujaikumar 's suggestion to get around the problem. Can you clarify?

Traceback (most recent call last):
  File "/home/plzad/blobtoolkit/blobtools2/lib/add.py", line 71, in <module>
    import bed
  File "/home/plzad/blobtoolkit/blobtools2/lib/bed.py", line 16, in <module>
    from tolkein import tofile
ModuleNotFoundError: No module named 'tolkein'
