### ISSUE TITLE
blobtools create / add issue with NCBI taxdump

### ISSUE THREAD

**Issue by kmkocot** [blobtoolkit/blobtools2#32]
Hello,

I'm trying to create a new blobdir with blobtools v2.2.0 with the following command:
`blobtools create --fasta final.purged.fa.PolcaCorrected.fa.masked --taxid 2732485 --taxdump /home/wirenia/databases/taxdump_2021-06-14`

I downloaded that NCBI taxdump from here and extracted the contents into a folder with the above name: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz

I'm getting the following error:
`/taxdump_2021-06-14 Hanleya_BlobDir
Loading sequences from final.purged.fa.PolcaCorrected.fa.masked
 - processing scf7180000319630: : 62284it [02:54, 356.82it/s]
Parsing taxdump
Traceback (most recent call last):
  File "/home/wirenia/bin/blobtools2/lib/add.py", line 153, in <module>
    main()
  File "/home/wirenia/bin/blobtools2/lib/add.py", line 147, in main
    taxdump = fetch_taxdump(args['--taxdump'])
  File "/home/wirenia/bin/blobtools2/lib/fetch.py", line 89, in fetch_taxdump
    taxdump = Taxdump(path_to_taxdump)
  File "/home/wirenia/bin/blobtools2/lib/taxdump.py", line 30, in __init__
    self.load_ancestors()
  File "/home/wirenia/bin/blobtools2/lib/taxdump.py", line 60, in load_ancestors
    for line in file_io.stream_file(filename):
TypeError: 'NoneType' object is not iterable`

I assume this is operator error but I'm not sure what I'm doing wrong. Any advice would be welcome.

Thanks!
Kevin

**Comment by rjchallis** [comment]
Hi Kevin

That link is not the taxdump - you'll need to fetch it from https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz

**Comment by kmkocot** [comment]
Thanks!! I figured it was operator error!

**Comment by Scenery6688** [comment]
> Thanks!! I figured it was operator error!

Hi Kevin,

I encountered the same issues with yours when i run 'blobtools create'. Could you please tell me how you solved this problem? Thanks in advance.

Best,
Jingli

**Comment by tol-training** [comment]
Hi Jingli - as rjchallis commented at https://github.com/blobtoolkit/blobtoolkit/issues/32#issuecomment-861251066 - you need to download and tar gunzip the latest ncbi taxdump into a folder (i used the example `./taxdump` below but it can be any folder) and point to that folder using the `--taxdump` option during your `blobtools create` command.

Eg:
```
mkdir ./taxdump
curl https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz | tar xzf - -C ./taxdump

blobtools create --fasta assemblyname.fasta --meta config.yaml --taxid 1261509 --taxdump ./taxdump/ /path/to/blobdirs/assemblyname
```

Hope this helps

**Comment by Scenery6688** [comment]
Thanks for your reply, Kevin. I have downloaded and used this updated verson taxdump, but it still didn't work on my MacOS Desktop. It shows the following errors when run 'blontools create --fasta assemblyname.fasta --meta config.yaml --taxdump ./taxdump/ ./blobdirs/assemblyname':Traceback (most recent call last):
  File "/Users/xuanjingli/program/contaminnats/blobtoolkit/blobtools2/lib/add.py", line 189, in <module>
    main()
  File "/Users/xuanjingli/program/contaminnats/blobtoolkit/blobtools2/lib/add.py", line 116, in main
    meta = fetch_metadata(args["DIRECTORY"], **args)
  File "/Users/xuanjingli/program/contaminnats/blobtoolkit/blobtools2/lib/fetch.py", line 71, in fetch_metadata
    for key, value in new_meta.items():
AttributeError: 'NoneType' object has no attribute 'items'

Do you have any advice to solve these problems above? Thanks so much in advance.

Best
