### ISSUE TITLE
Viewer issues

### ISSUE THREAD

**Issue by Mondlii** [blobtoolkit/blobtools2#39]
Hi, 

I was hoping to get some assistance with an issue I have been getting with the viewer lately. I have run all the commands as in the tutorial and everything seems as is on the docs. I have an issue with running ```blobtooklit/blobtools view --interactive /blodir```
This is able to launch a viewer instance but it gets stuck on an infinite loading page. I even left it on for a day and nothing. Please assist. Thank you

Kind regards,
Mondli 

![Screenshot 2021-10-14 160940](https://user-images.githubusercontent.com/81998129/137334881-decbf87d-d9a0-41df-ac6e-36b22f466cba.png)

**Comment by rjchallis** [comment]
Hi

Sorry, the dependencies listed on the install page seem to be out of date so I think this may be caused by the version of nodes that you are using. The viewer now needs node version 14 rather than 10 so I'll need to update that page.

The most up to date instructions are at https://github.com/blobtoolkit/pipeline, and the relevant instructions for the viewer are
```
conda install -y -n base -c conda-forge mamba

sudo apt update && sudo apt-get -y install firefox xvfb

conda activate btk_env
mamba install -y -c conda-forge geckodriver selenium pyvirtualdisplay nodejs=14
pip install fastjsonschema;
```

**Comment by Mondlii** [comment]
Apologies for the late response, it turns out the issue is with my OS. I can work around this by viewing the whole blobtoolkit folder.

Thank you very much.

**Comment by Mondlii** [comment]
Sorry for reopening this closed issue, but I felt it would not be productive to add another issue, but I am having an issue with the busco output in viewer. I used the full table as suggested, but the complete % is somehow higher than in the short_report from busco. 

On the short report I get 92%: 
![Screenshot from 2021-11-14 15-55-57](https://user-images.githubusercontent.com/81998129/141684221-12743072-cb9f-414e-8c5c-07e48d3696a1.png)

But on the viewer output I get this 94%: 
![Acacia_draft embryophyta_odb10_busco busco(1)](https://user-images.githubusercontent.com/81998129/141684245-86205e87-ed0e-4a8d-bbf5-719125b57959.png)

Is this correct or am I misreading the viewer output? Thank you.

**Comment by rjchallis** [comment]
Glad you got the viewer working. 

I'm not sure why the BUSCO appears to be higher - could you give me some more information so I can work what is happening:

- Which busco version/ lineage dataset is this?
- What values are reported in the busco table in the viewer?
- Can you share the busco full table output and the associated JSON file from the BlobDir. The file name will be like `eukaryota_odb10_busco.json`

**Comment by Mondlii** [comment]
HI, apologies for the late response. I had an issue with getting the busco folder from the server.

1. I used embryophyta odb10
2. The busco table on the viewer reports exactly what's on the graph above
3. Please see below the json file in txt format for easy upload. 
[embryophyta_odb10_busco.json.txt](https://github.com/blobtoolkit/blobtools2/files/7601801/embryophyta_odb10_busco.json.txt)

Thank you

**Comment by rjchallis** [comment]
Sorry for taking so long to reply - I didn't spot the full_table file when I first looked at this. Now I've checked the files it looks most likely that there is an error in the BUSCO short summary or perhaps a file mixup as there are no fragmented BUSCOs in the full_table.tsv.txt. 

Both of the files you sent have 1530 complete BUSCOs, not 1488 as reported in the summary table, so the current score appears to be around 94.8%:

```
$ grep Complete full_table.tsv.txt | cut -f 1 | sort | uniq | wc -l
    1530
$ grep at3193 embryophyta_odb10_busco.json.txt | cut -d '"' -f 2 | sort | uniq | wc -l
    1530
```

**Comment by Mondlii** [comment]
Apologies for the late response, only recently did my holiday end. Thank you for your help, I will try and fix the busco issues or use a different version and see what the outcome is.
