### ISSUE TITLE
Filtering fastq returns single line file

### ISSUE THREAD

**Issue by pgonzale60** [blobtoolkit/blobtools2#4]
Hi Rich,

I want to get the reads that align to the non-contaminant sources so that I can assemble these clean reads. I issue the following commands to do so.

`./blobtools2/blobtools filter --query-string "http://localhost:8080/view/all/dataset/hs_Omyriophila/blob?bestsumorder_phylum--Keys=2&srtd_cov--Min=0.0100&srtd_cov--Max=300#Filters" --fastq ../fastp/hs_Omyriophila_trimmed_1.fastq.gz --fastq ../fastp/hs_Omyriophila_trimmed_2.fastq.gz --cov ../bwa/hs_Omyriophila.srtd.bam hs_Omyriophila`

But the content of ../fastp/hs_Omyriophila_trimmed_1.fastq.filtered.gz according to `cat` is: 
> ��w]�hs_Omyriophila_trimmed_1.fastq.filtered��

(The original fastq read files are sane.)
What went wrong?

Cheers,
Pablo

**Comment by rjchallis** [comment]
I'm unable to reproduce this. Not sure if it was related to #5 - are you still seeing this behaviour with the latest commit?
